// Generate supabase/seed.sql from content.json.
// Splits the curriculum into PUBLIC (free preview/marketing) and PAID rows.
// Run: node content/seed.mjs   ->   writes supabase/seed.sql
import fs from 'fs';

const d = JSON.parse(fs.readFileSync(new URL('./content.json', import.meta.url)));
const SAMPLE = 'llm'; // the one module offered free as a sample

const rows = [];
const add = (id, tier, data) => rows.push({ id, tier, data });

// ---- PUBLIC: browsable catalog + marketing copy + one full sample module ----
add('meta:blocks', 'public', d.BLOCKS);
add('meta:catalog', 'public', d.MODULES.map(m => ({
  id: m.id, block: m.block, title: m.title, tag: m.tag, why: m.why,
  isNew: !!m.isNew, isUpd: !!m.isUpd, estMin: m.estMin
})));
add('glossary', 'public', d.GLOSSARY);
add('plain', 'public', d.PLAIN);

// ---- per-module bundles (sample module is public, the rest are paid) ----
for (const m of d.MODULES) {
  const tier = m.id === SAMPLE ? 'public' : 'paid';
  add('module:' + m.id, tier, {
    mod: m,
    deep: d.DEEP[m.id] || null,
    depth: d.DEPTH[m.id] || null,
    patterns: d.PATTERNS[m.id] || null
  });
  add('quiz:' + m.id, tier, d.QUIZ[m.id] || []);
}

// ---- shared paid collections ----
add('cards', 'paid', d.CARDS);
add('scenarios', 'paid', d.SCENARIOS);

// ---- emit SQL ----
const sqlVal = obj => "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb";
let out = '-- Generated by content/seed.mjs. Do not edit by hand.\n';
out += '-- Seeds public.content. Safe to re-run (upsert on id).\n\n';
for (const r of rows) {
  out += `insert into public.content (id, tier, data) values ('${r.id}', '${r.tier}', ${sqlVal(r.data)})\n`;
  out += `  on conflict (id) do update set tier = excluded.tier, data = excluded.data, updated_at = now();\n`;
}
fs.writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out);

const pub = rows.filter(r => r.tier === 'public').length;
const paid = rows.filter(r => r.tier === 'paid').length;
console.log(`wrote supabase/seed.sql — ${rows.length} rows (${pub} public, ${paid} paid)`);
