// Generate supabase/seed.sql from the per-course content JSON files.
// Splits each course's curriculum into PUBLIC (free preview/marketing) and PAID
// rows, scoped by course_id (migration 0003). Run: node content/seed.mjs
//
// Multi-course: emits BOTH courses into one seed.sql. ai-eng must stay byte-for-
// byte identical to the single-course era (it's already in production); ai-
// foundations rows are appended alongside with the same row-id / tier conventions.
// Row assembly + validators are shared with app-next/scripts/seed-db.mjs via
// build-rows.mjs.
import fs from 'fs';
import { runValidators, loadCourses, buildRows } from './build-rows.mjs';

runValidators();

const COURSES = loadCourses();

// ---- emit SQL (both courses) ----
const sqlVal = obj => "'" + JSON.stringify(obj).replace(/'/g, "''") + "'::jsonb";
let out = '-- Generated by content/seed.mjs. Do not edit by hand.\n';
out += `-- Seeds public.content for courses: ${COURSES.map(c => "'" + c.course + "'").join(', ')}. Safe to re-run (upsert on course_id,id).\n`;
out += '-- Requires migration 0003 (course_id column + courses anchor rows).\n\n';

let total = 0, totalPub = 0;
for (const c of COURSES) {
  const rows = buildRows(c);
  const pub = rows.filter(r => r.tier === 'public').length;
  out += `-- ===== course '${c.course}': ${rows.length} rows (${pub} public, ${rows.length - pub} paid) =====\n`;
  for (const r of rows) {
    out += `insert into public.content (course_id, id, tier, data) values ('${c.course}', '${r.id}', '${r.tier}', ${sqlVal(r.data)})\n`;
    out += `  on conflict (course_id, id) do update set tier = excluded.tier, data = excluded.data, updated_at = now();\n`;
  }
  out += '\n';
  total += rows.length; totalPub += pub;
  console.log(`  course '${c.course}': ${rows.length} rows (${pub} public, ${rows.length - pub} paid)`);
}

fs.writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out);
console.log(`wrote supabase/seed.sql — ${total} rows total (${totalPub} public, ${total - totalPub} paid) across ${COURSES.length} course(s)`);
