// GENERATED by video/scripts/gen-videos.mjs — do not edit by hand.
// Source: video/data/prefaces.mjs (scripts) + rendered durations.
// Sparse preface-video registry: only modules that have been rendered + uploaded.
// Seeded as the public `videos` content row by both seed paths.

export const VIDEOS = {
  "context": {
    "src": "context/preface.mp4",
    "poster": "context/preface.jpg",
    "vtt": "context/preface.en.vtt",
    "duration": 41,
    "tier": "public",
    "title": "Curating what the model sees",
    "caption": "A short preface — why what the model sees matters more than how you phrase it."
  },
  "rag": {
    "src": "rag/preface.mp4",
    "poster": "rag/preface.jpg",
    "vtt": "rag/preface.en.vtt",
    "duration": 54,
    "tier": "public",
    "title": "Why retrieval beats a bigger prompt",
    "caption": "A short preface — the problem RAG actually solves, before we get into how it works."
  },
  "embed": {
    "src": "embed/preface.mp4",
    "poster": "embed/preface.jpg",
    "vtt": "embed/preface.en.vtt",
    "duration": 44,
    "tier": "public",
    "title": "Meaning as geometry",
    "caption": "A short preface — the intuition behind meaning-as-geometry, before the engineering."
  },
  "agents": {
    "src": "agents/preface.mp4",
    "poster": "agents/preface.jpg",
    "vtt": "agents/preface.en.vtt",
    "duration": 38,
    "tier": "public",
    "title": "An LLM in a loop",
    "caption": "A short preface — what an agent is, and why reliability comes from the loop."
  },
  "evals": {
    "src": "evals/preface.mp4",
    "poster": "evals/preface.jpg",
    "vtt": "evals/preface.en.vtt",
    "duration": 38,
    "tier": "public",
    "title": "Shipping, not guessing",
    "caption": "A short preface — why evals are what separate shipping from guessing."
  }
};
