// Generate the apps' preface-video registries from the rendered output. A module
// is included only if it has been rendered locally (public/<dir>/props.json
// exists), so the app never references a missing file.
//
//   node scripts/gen-videos.mjs
//
// Multi-course: each course has its own prefaces source + its own videos.mjs
// registry (the app reads one `videos` content row per course_id). Module ids can
// collide across courses (e.g. `context`, `tools` exist in both), so AI
// Foundations renders into a namespaced public dir (af-<id>) to keep files apart.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PREFACES as MASTERY } from "../data/prefaces.mjs";
import { PREFACES as FOUNDATIONS } from "../data/prefaces-ai-foundations.mjs";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const REPO = path.resolve(ROOT, "..");

// course -> { prefaces, out, dir(id), header-note }. `dir` maps a module id to
// the render/public subdir + the in-app src path prefix.
const COURSES = [
  {
    name: "ai-eng",
    prefaces: MASTERY,
    out: path.join(REPO, "content", "videos.mjs"),
    dir: (id) => id, // Mastery renders into public/<id>/
    sourceNote: "video/data/prefaces.mjs (scripts) + rendered durations.",
  },
  {
    name: "ai-foundations",
    prefaces: FOUNDATIONS,
    out: path.join(REPO, "content", "videos-ai-foundations.mjs"),
    dir: (id) => `af-${id}`, // namespaced so ids can't collide with Mastery's
    sourceNote: "video/data/prefaces-ai-foundations.mjs (scripts) + rendered durations.",
  },
];

for (const c of COURSES) {
  const entries = {};
  for (const id of Object.keys(c.prefaces)) {
    const sub = c.dir(id);
    const propsPath = path.join(ROOT, "public", sub, "props.json");
    if (!fs.existsSync(propsPath)) continue;
    const props = JSON.parse(fs.readFileSync(propsPath, "utf8"));
    entries[id] = {
      src: `${sub}/preface.mp4`,
      poster: `${sub}/preface.jpg`,
      vtt: `${sub}/preface.en.vtt`,
      duration: Math.round(props.durationInSeconds),
      tier: "public",
      title: c.prefaces[id].title,
      caption: c.prefaces[id].caption,
    };
  }

  const header = `// GENERATED by video/scripts/gen-videos.mjs — do not edit by hand.
// Source: ${c.sourceNote}
// Sparse preface-video registry: only modules that have been rendered + uploaded.
// Seeded as the public \`videos\` content row for the '${c.name}' course.
`;
  const body = `export const VIDEOS = ${JSON.stringify(entries, null, 2)};\n`;
  fs.writeFileSync(c.out, header + "\n" + body);

  const ids = Object.keys(entries);
  console.log(`✓ ${c.name}: wrote ${path.relative(REPO, c.out)} with ${ids.length} video(s)${ids.length ? ": " + ids.join(", ") : ""}`);
}
