// Generate content/videos.mjs (the app's preface-video registry) from the
// rendered output. A module is included only if it has been rendered locally
// (public/<id>/props.json exists), so the app never references a missing file.
//
//   node scripts/gen-videos.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PREFACES } from "../data/prefaces.mjs";

const ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const REPO = path.resolve(ROOT, "..");

const entries = {};
for (const id of Object.keys(PREFACES)) {
  const propsPath = path.join(ROOT, "public", id, "props.json");
  if (!fs.existsSync(propsPath)) continue;
  const props = JSON.parse(fs.readFileSync(propsPath, "utf8"));
  entries[id] = {
    src: `${id}/preface.mp4`,
    poster: `${id}/preface.jpg`,
    vtt: `${id}/preface.en.vtt`,
    duration: Math.round(props.durationInSeconds),
    tier: "public",
    title: PREFACES[id].title,
    caption: PREFACES[id].caption,
  };
}

const header = `// GENERATED by video/scripts/gen-videos.mjs — do not edit by hand.
// Source: video/data/prefaces.mjs (scripts) + rendered durations.
// Sparse preface-video registry: only modules that have been rendered + uploaded.
// Seeded as the public \`videos\` content row by both seed paths.
`;
const body = `export const VIDEOS = ${JSON.stringify(entries, null, 2)};\n`;
const out = path.join(REPO, "content", "videos.mjs");
fs.writeFileSync(out, header + "\n" + body);

console.log(`✓ wrote content/videos.mjs with ${Object.keys(entries).length} video(s): ${Object.keys(entries).join(", ")}`);
